version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build-and-test:
    macos:
      xcode: "14.2.0"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Install Swift
          command: |
            brew install swift@5.8  # Swiftのバージョンを指定
            echo 'export PATH="/usr/local/opt/swift@5.8/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
