version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build-and-test:
    macos:
      xcode: "15.0"
      resource_class: medium
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
