version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    macos:
      xcode: "16.0"
    working_directory: /RideLink
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
    
      - run:
          name: Create directory if it doesn't exist
          command: mkdir -p /Users/sawakishuto/RideLink  # 必要に応じて適切なパスに変更
      
      - checkout
      
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
