default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      devices: ["iPhone 15"],  # デバイス名を確認
      include_simulator_logs: false
    )
  end
end
