default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
  
  # Swiftのバージョン確認
scan(
      devices: ["iPhone 14 Pro"],  # デバイス名を確認
      include_simulator_logs: false
    )
  end
end
